global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus-prod:9090"]

  - job_name: "anpr-micro"
    static_configs:
      - targets: ["anpr-micro-prod:8000"]
