# DevOps/staging/docker-compose.yml
name: anprvision-micro-staging
version: "3.9"

services:
  # ðŸ§  Worker principal (ANPR Vision Microservice)
  anpr-worker-staging:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: anpr-worker-staging
    env_file:
      - .env
    working_dir: /app
    command: python -m src.workers.main_worker
    networks:
      - anpr-net-staging
    tty: true
    restart: unless-stopped

  # ðŸ“Š Prometheus
  prometheus-staging:
    image: prom/prometheus:latest
    container_name: prometheus-staging
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - anpr-net-staging
    restart: unless-stopped

  # ðŸ“ˆ Grafana
  grafana-staging:
    image: grafana/grafana:latest
    container_name: grafana-staging
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS}
    volumes:
      - grafana_staging:/var/lib/grafana
    networks:
      - anpr-net-staging
    restart: unless-stopped


# ===============================
# VolÃºmenes persistentes
# ===============================
volumes:
  grafana_staging:

# ===============================
# Red interna del entorno
# ===============================
networks:
  anpr-net-staging:
    external: true
