name: anpr-micro-prod
version: "3.9"

services:

  anpr-micro:
    image: anpr-microservice-prod:latest
    container_name: anpr-micro-prod
    env_file:
      - .env
    command: python -m src.workers.main_worker
    networks:
      - anpr-net-prod
    restart: unless-stopped
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 20s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-prod
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"  # prod local -> queremos verlo en localhost
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.listen-address=:9090'
    networks:
      - anpr-net-prod
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-prod
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS}
    volumes:
      - grafana_prod:/var/lib/grafana
    ports:
      - "3000:3000"  # prod local -> queremos verlo en localhost
    networks:
      - anpr-net-prod
    restart: unless-stopped

networks:
  anpr-net-prod:
    external: true

volumes:
  grafana_prod:
