# DevOps/develop/docker-compose.yml
name: anprvision-micro-develop
version: "3.9"

services:
  # ðŸ§  Worker principal (ANPR Vision Microservice)
  anpr-worker-develop:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: anpr-worker-develop
    env_file:
      - .env
    working_dir: /app
    command: python -m src.workers.main_worker
    networks:
      - anpr-net-develop
    tty: true
    restart: unless-stopped
    volumes:
      - ../../:/app   # opcional para desarrollo

  # ðŸ“Š Prometheus
  prometheus-develop:
    image: prom/prometheus:latest
    container_name: prometheus-develop
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"
    networks:
      - anpr-net-develop
    restart: unless-stopped

  # ðŸ“ˆ Grafana
  grafana-develop:
    image: grafana/grafana:latest
    container_name: grafana-develop
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS}
    volumes:
      - grafana_develop:/var/lib/grafana
    networks:
      - anpr-net-develop
    restart: unless-stopped


# ===============================
# VolÃºmenes persistentes
# ===============================
volumes:
  grafana_develop:

# ===============================
# Red interna del entorno
# ===============================
networks:
  anpr-net-develop:
    external: true
